"""LangGraph Pod 節點：re-export shim。

實際定義搬到 nodes_research.py / nodes_writer.py / nodes_judge.py /
nodes_episode.py（依 pipeline 階段切分，共用工具見 nodes_common.py）。
這層 shim 存在是因為 graph.py 跟大量測試檔案直接
`from engine.pipeline.langgraph_pod.nodes import X`，搬檔不需要動這些 import path。
"""

from __future__ import annotations

from shared.db import repo as app_repo

from .nodes_common import (
    _collector,
    _ctx,
    _record_llm_usage,
    _usage_from_ai_msg,
)
from .nodes_episode import (
    _slugify,
    _source_metadata,
    backfill_dict_node,
    dead_letter_node,
    insert_deliveries_node,
    render_branch_decision,
    render_episode_node,
    storage_decision,
    update_episode_keys_node,
    upload_artifacts_node,
    upsert_episode_node,
)
from .nodes_judge import (
    _apply_best_draft_fallback,
    _empty_claim_verification,
    _identify_affected_segments,
    _judge_passed,
    judge_decision,
    quality_judge_node,
    rewrite_iteration_bump_node,
    verify_script_claims_node,
)
from .nodes_research import (
    _evidence_source_type,
    _fallback_research_questions,
    _unverified_claims,
    cross_verify_node,
    decompose_research_node,
    gather_evidence_node,
    resolve_format,
    tone_selector_node,
)
from .nodes_writer import (
    _build_outline_messages,
    _build_segment_messages,
    _generate_outline,
    _generate_segment,
    _invoke_writer,
    _merge_outline_and_segments,
    _normalize_line_lengths,
    _parse_outline,
    _parse_segment_script,
    _script_word_count,
    _segment_word_targets,
    _series_block,
    _shared_style_prefix,
    _sources_block,
    _structure_block,
    _TierConfig,
    _to_lc_messages,
    _verified_research_block,
    _word_floor,
    _word_target,
    failover_decision,
    failover_write_script_node,
    rate_limit_decision,
    write_script_node,
)

__all__ = [
    "app_repo",
    "_TierConfig",
    "_apply_best_draft_fallback",
    "_build_outline_messages",
    "_build_segment_messages",
    "_collector",
    "_ctx",
    "_empty_claim_verification",
    "_evidence_source_type",
    "_fallback_research_questions",
    "_generate_outline",
    "_generate_segment",
    "_identify_affected_segments",
    "_invoke_writer",
    "_judge_passed",
    "_merge_outline_and_segments",
    "_normalize_line_lengths",
    "_parse_outline",
    "_parse_segment_script",
    "_record_llm_usage",
    "_script_word_count",
    "_segment_word_targets",
    "_series_block",
    "_shared_style_prefix",
    "_slugify",
    "_source_metadata",
    "_sources_block",
    "_structure_block",
    "_to_lc_messages",
    "_unverified_claims",
    "_usage_from_ai_msg",
    "_verified_research_block",
    "_word_floor",
    "_word_target",
    "backfill_dict_node",
    "cross_verify_node",
    "dead_letter_node",
    "decompose_research_node",
    "failover_decision",
    "failover_write_script_node",
    "gather_evidence_node",
    "insert_deliveries_node",
    "judge_decision",
    "quality_judge_node",
    "rate_limit_decision",
    "render_branch_decision",
    "render_episode_node",
    "resolve_format",
    "rewrite_iteration_bump_node",
    "storage_decision",
    "tone_selector_node",
    "update_episode_keys_node",
    "upload_artifacts_node",
    "upsert_episode_node",
    "verify_script_claims_node",
    "write_script_node",
]
