/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/vocab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vocab */
        get: operations["list_vocab_vocab_get"];
        put?: never;
        /**
         * Add Vocab
         * @description 新增；去重鍵 unique(user_id,lemma,source_episode_id,source_line_no)。
         *
         *     衝突時回既有列（對齊 mockApi 行為）。slug→uuid 轉換在此。
         */
        post: operations["add_vocab_vocab_post"];
        /** Clear Vocab */
        delete: operations["clear_vocab_vocab_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocab/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Vocab */
        get: operations["search_vocab_vocab_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocab/{vocab_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Vocab */
        delete: operations["remove_vocab_vocab__vocab_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Vocab
         * @description 更新 SM-2 欄位（nextReview/interval/ease）。只動本人列。
         */
        patch: operations["update_vocab_vocab__vocab_id__patch"];
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings Ep */
        get: operations["get_settings_ep_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Settings Ep
         * @description upsert：以預設列為底，coalesce 套用 patch 有給的欄位。
         */
        patch: operations["update_settings_ep_settings_patch"];
        trace?: never;
    };
    "/settings/reset-popup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Popup Preferences */
        post: operations["reset_popup_preferences_settings_reset_popup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Favorites */
        get: operations["list_favorites_favorites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Favorite */
        post: operations["add_favorite_favorites__slug__post"];
        /** Remove Favorite */
        delete: operations["remove_favorite_favorites__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-orders/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Daily Order */
        get: operations["get_daily_order_daily_orders__date__get"];
        put?: never;
        post?: never;
        /** Delete Daily Order */
        delete: operations["delete_daily_order_daily_orders__date__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Daily Orders */
        get: operations["list_daily_orders_daily_orders_get"];
        /**
         * Save Daily Order
         * @description upsert 整筆訂單（key = user_id + date）。
         */
        put: operations["save_daily_order_daily_orders_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-orders/{date}/played": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Order Played
         * @description 標記已播放。找不到回 null（對齊 mockApi）。
         */
        post: operations["mark_order_played_daily_orders__date__played_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-orders/{date}/episode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Daily Order Episode
         * @description 取當天交付給該 user 的集數，找不到回 null（前端 fallback 到 listEpisodes()[0]）。
         *
         *     URL 語意：daily_order 是主資源，episode 是其子資源（解決 PlayerRoute 點 ?date=
         *     連結時不知道播哪集的問題）。
         */
        get: operations["get_daily_order_episode_daily_orders__date__episode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Episodes
         * @description 免費集，或該 user 有 delivery 授權的集數。
         */
        get: operations["list_episodes_episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Episode */
        get: operations["get_episode_episodes__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/{slug}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Episode Url
         * @description 產 R2 簽章 URL。先驗授權（免費或有 delivery），通過才 presign。
         *
         *     本機 fallback：當 R2 key 為 NULL 且 LOCAL_MEDIA_DIR 設定時，回 /media/{slug}.mp3
         *     （router 只關 mp3，不再產 mp4）。
         */
        get: operations["get_episode_url_episodes__slug__url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dict/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Dict */
        get: operations["lookup_dict_dict_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity Ep */
        get: operations["get_activity_ep_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Activity Ep */
        patch: operations["patch_activity_ep_activity_patch"];
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me Ep */
        get: operations["get_me_ep_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me Ep
         * @description 刪除本人帳號。FK ON DELETE CASCADE 自動清 8 張 child tables。
         *
         *     整個 DELETE 在同一 connection / 同一 transaction 內執行（commit 1 次），
         *     任一步失敗 → psycopg context manager 自動 rollback，無半毀狀態。
         */
        delete: operations["delete_me_ep_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Admin Episodes
         * @description Debug 用集數清單，含 hasAudio（audio_r2_key 是否已寫入）判斷生成是否完成。
         */
        get: operations["list_admin_episodes_admin_episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Admin Jobs
         * @description 所有 pgmq 佇列的度量（metrics_all，不硬寫佇列名，新增佇列免改程式碼）。
         */
        get: operations["list_admin_jobs_admin_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/token-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin Token Usage
         * @description token 用量總覽：全集數 input/output 加總 + 最近 50 筆明細。
         */
        get: operations["get_admin_token_usage_admin_token_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/orders/{date}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Order Generate
         * @description 送一筆 control orchestrate 給 worker，觸發當日 episode pipeline。
         *
         *     回 202 Accepted：job 已 enqueue，不代表已生成；GET /daily-orders/{date}/episode
         *     輪詢結果。
         */
        post: operations["trigger_order_generate_jobs_orders__date__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending Notifications
         * @description 目前該收到出餐通知的使用者清單（唯讀觀測，尚未接上實際寄送）。
         */
        get: operations["list_pending_notifications_notifications_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountInfo
         * @description GET /me 回傳欄位。id / email / tz / delivery_time / created_at。
         *
         *     email 從 JWT payload 解（Supabase 預設 JWT 帶 email claim）；
         *     其餘欄位從 public.users SELECT。handle_new_user trigger 尚未補列時，
         *     tz / delivery_time / created_at 採 DB 預設值，router 端不必補空字串。
         */
        AccountInfo: {
            /** Id */
            id: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Tz
             * @default Asia/Taipei
             */
            tz: string;
            /**
             * Deliverytime
             * @default 07:00
             */
            deliveryTime: string;
            /**
             * Createdat
             * @default
             */
            createdAt: string;
        };
        /**
         * Activity
         * @description 學習進度上雲（T2）。四個累積型欄位 + 播放進度快照，跨裝置同步。
         *
         *     PATCH 端點做「合併」而非「取代」；此模型是合併後（或無列時的預設）快照。
         */
        Activity: {
            /** Streakdates */
            streakDates?: string[];
            /** Listenminutes */
            listenMinutes?: {
                [key: string]: number;
            };
            /** Lookupcount */
            lookupCount?: {
                [key: string]: number;
            };
            /** Listenedepisodeids */
            listenedEpisodeIds?: string[];
            /** Lastplayedepisodeid */
            lastPlayedEpisodeId?: string | null;
            /** Lastplayedposition */
            lastPlayedPosition?: number | null;
            /** Lastplayedat */
            lastPlayedAt?: string | null;
        };
        /**
         * AddVocabBody
         * @description 對齊前端 Omit<VocabItem,'id'|'createdAt'>。
         *
         *     SM-2 欄位（nextReview/interval/ease）由 server 設預設，前端送的忽略。
         */
        AddVocabBody: {
            /** Word */
            word: string;
            /** Lemma */
            lemma: string;
            /** Pos */
            pos?: string | null;
            /** Translation */
            translation: string;
            /** Ipa */
            ipa?: string | null;
            /** Sourceepisodeid */
            sourceEpisodeId: string;
            /** Sourcelineno */
            sourceLineNo: number;
            /** Sourcetimestamp */
            sourceTimestamp: number;
            /**
             * Senseidx
             * @default 0
             */
            senseIdx: number;
            /** Sourcesentence */
            sourceSentence?: string | null;
            /** Sourcesentencezh */
            sourceSentenceZh?: string | null;
        };
        /**
         * AdminEpisode
         * @description admin debug 用集數清單項。hasAudio 用 audio_r2_key 是否已寫入代理生成完成訊號。
         */
        AdminEpisode: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Topic */
            topic: string;
            /**
             * Cefrlevel
             * @default B1
             */
            cefrLevel: string;
            /**
             * Isfree
             * @default false
             */
            isFree: boolean;
            /**
             * Isfeatured
             * @default false
             */
            isFeatured: boolean;
            /**
             * Episodeno
             * @default 0
             */
            episodeNo: number;
            /**
             * Publishedat
             * @default
             */
            publishedAt: string;
            /** Createdat */
            createdAt: string;
            /**
             * Freshnessclass
             * @default evergreen
             */
            freshnessClass: string;
            /** Expiresat */
            expiresAt?: string | null;
            /**
             * Hasaudio
             * @default false
             */
            hasAudio: boolean;
        };
        /**
         * AdminJobQueue
         * @description 單一 pgmq 佇列的度量（pgmq.metrics_all() 逐列對映）。
         *
         *     空佇列時 pgmq 可能回 NULL age，故後三欄允許 None。
         */
        AdminJobQueue: {
            /** Queuename */
            queueName: string;
            /** Queuelength */
            queueLength: number;
            /** Newestmsgagesec */
            newestMsgAgeSec?: number | null;
            /** Oldestmsgagesec */
            oldestMsgAgeSec?: number | null;
            /** Totalmessages */
            totalMessages?: number | null;
        };
        /** AdminTokenUsageItem */
        AdminTokenUsageItem: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Inputtokens
             * @default 0
             */
            inputTokens: number;
            /**
             * Outputtokens
             * @default 0
             */
            outputTokens: number;
            /** Createdat */
            createdAt: string;
        };
        /** AdminTokenUsageResponse */
        AdminTokenUsageResponse: {
            /**
             * Totalinputtokens
             * @default 0
             */
            totalInputTokens: number;
            /**
             * Totaloutputtokens
             * @default 0
             */
            totalOutputTokens: number;
            /**
             * Episodecount
             * @default 0
             */
            episodeCount: number;
            /** Items */
            items?: components["schemas"]["AdminTokenUsageItem"][];
        };
        /** ApiResponse[AccountInfo] */
        ApiResponse_AccountInfo_: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["AccountInfo"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[Activity] */
        ApiResponse_Activity_: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["Activity"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[AdminTokenUsageResponse] */
        ApiResponse_AdminTokenUsageResponse_: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["AdminTokenUsageResponse"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[DailyOrder] */
        ApiResponse_DailyOrder_: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["DailyOrder"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[Episode] */
        ApiResponse_Episode_: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["Episode"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[NoneType] */
        ApiResponse_NoneType_: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[Settings] */
        ApiResponse_Settings_: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["Settings"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[Union[DailyOrder, NoneType]] */
        ApiResponse_Union_DailyOrder__NoneType__: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["DailyOrder"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[Union[DictEntry, NoneType]] */
        ApiResponse_Union_DictEntry__NoneType__: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["DictEntry"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[Union[Episode, NoneType]] */
        ApiResponse_Union_Episode__NoneType__: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["Episode"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[VocabItem] */
        ApiResponse_VocabItem_: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["VocabItem"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[dict[str, str]] */
        ApiResponse_dict_str__str__: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: {
                [key: string]: string;
            } | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[list[AdminEpisode]] */
        ApiResponse_list_AdminEpisode__: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: components["schemas"]["AdminEpisode"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[list[AdminJobQueue]] */
        ApiResponse_list_AdminJobQueue__: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: components["schemas"]["AdminJobQueue"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[list[DailyOrder]] */
        ApiResponse_list_DailyOrder__: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: components["schemas"]["DailyOrder"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[list[EpisodeListItem]] */
        ApiResponse_list_EpisodeListItem__: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: components["schemas"]["EpisodeListItem"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[list[PendingNotificationOut]] */
        ApiResponse_list_PendingNotificationOut__: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: components["schemas"]["PendingNotificationOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[list[VocabItem]] */
        ApiResponse_list_VocabItem__: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: components["schemas"]["VocabItem"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[list[str]] */
        ApiResponse_list_str__: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: string[] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ApiResponse[str] */
        ApiResponse_str_: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: string | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Cue */
        Cue: {
            /** Index */
            index: number;
            /** Speaker */
            speaker: string;
            /** Text */
            text: string;
            /** Zh */
            zh: string;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** DailyOrder */
        DailyOrder: {
            /** Date */
            date: string;
            /** Selectedtopics */
            selectedTopics?: string[];
            /** Specificrequest */
            specificRequest?: string | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "queued" | "played";
            /**
             * Deliverytime
             * @default 07:00
             */
            deliveryTime: string;
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
            /** Playedat */
            playedAt?: string | null;
            /**
             * Entrymode
             * @default topic
             * @enum {string}
             */
            entryMode: "news" | "topic" | "knowledge" | "skill";
            /**
             * Lengthtier
             * @default medium
             * @enum {string}
             */
            lengthTier: "short" | "medium" | "long";
        };
        /** DictEntry */
        DictEntry: {
            /** Word */
            word: string;
            /** Ipa */
            ipa?: string | null;
            /** Pos */
            pos?: string[];
            /** Translation */
            translation: string;
            /** Exchange */
            exchange?: string | null;
            /** Audiourl */
            audioUrl?: string | null;
            /** Exampleen */
            exampleEn?: string | null;
            /** Examplezh */
            exampleZh?: string | null;
        };
        /**
         * Episode
         * @description 前端播放頁需要的集數內容。audioUrl 由服務層產簽章 URL 後填入。
         */
        Episode: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Titlezh */
            titleZh?: string | null;
            /** Topic */
            topic: string;
            /**
             * Cefrlevel
             * @default B1
             */
            cefrLevel: string;
            /**
             * Isfree
             * @default false
             */
            isFree: boolean;
            /** Audiourl */
            audioUrl?: string | null;
            /** Cues */
            cues?: components["schemas"]["Cue"][];
        };
        /**
         * EpisodeListItem
         * @description 集數列表項，鏡像前端 MockEpisode（列表頁用，不含 cues / audioUrl）。
         *
         *     title_zh / episode / published_at 在 DB 可為 NULL，但前端 zod 要求非空，
         *     故查詢端一律 coalesce 出預設值（見 episodes.list_episodes）。
         */
        EpisodeListItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Titlezh
             * @default
             */
            titleZh: string;
            /** Topic */
            topic: string;
            /**
             * Cefrlevel
             * @default B1
             */
            cefrLevel: string;
            /**
             * Isfree
             * @default false
             */
            isFree: boolean;
            /**
             * Isfeatured
             * @default false
             */
            isFeatured: boolean;
            /**
             * Episode
             * @default 0
             */
            episode: number;
            /**
             * Publishedat
             * @default
             */
            publishedAt: string;
        };
        /**
         * ErrorBody
         * @description 對外錯誤只含 code/message，不洩漏 stack trace / SQL / 內部路徑。
         */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LastPlayedInput
         * @description 播放進度快照。at 是事件發生時間（ISO 8601），用來擋亂序節流請求覆蓋新進度。
         */
        LastPlayedInput: {
            /** Episodeid */
            episodeId: string;
            /** Position */
            position: number;
            /** At */
            at: string;
        };
        /**
         * ListenMinutesDelta
         * @description addListenMinutes 的增量輸入：指定月份要「加上」的分鐘數（非取代）。
         */
        ListenMinutesDelta: {
            /** Month */
            month: string;
            /** Minutes */
            minutes: number;
        };
        /**
         * LookupCountDelta
         * @description addLookupCount 的增量輸入：指定月份要「加上」的查詞次數（非取代）。
         */
        LookupCountDelta: {
            /** Month */
            month: string;
            /** Count */
            count: number;
        };
        /**
         * MarkPlayedBody
         * @description markOrderPlayed(date, playedAt) 的 body 部分（date 走 path）。
         */
        MarkPlayedBody: {
            /** Playedat */
            playedAt: string;
        };
        /**
         * PatchActivityBody
         * @description patchActivity(patch)。全 optional，皆為「增量」語意，只合併有給的欄位。
         */
        PatchActivityBody: {
            /** Addstreakdate */
            addStreakDate?: string | null;
            /** Addlistenedepisodeid */
            addListenedEpisodeId?: string | null;
            addListenMinutes?: components["schemas"]["ListenMinutesDelta"] | null;
            addLookupCount?: components["schemas"]["LookupCountDelta"] | null;
            lastPlayed?: components["schemas"]["LastPlayedInput"] | null;
        };
        /** PendingNotificationOut */
        PendingNotificationOut: {
            /** Userid */
            userId: string;
            /** Deliverytime */
            deliveryTime: string;
        };
        /**
         * SaveDailyOrderBody
         * @description saveDailyOrder(order)。前端送完整 DailyOrder；date 為 key。
         */
        SaveDailyOrderBody: {
            /** Date */
            date: string;
            /** Selectedtopics */
            selectedTopics?: string[];
            /** Specificrequest */
            specificRequest?: string | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "queued" | "played";
            /**
             * Deliverytime
             * @default 07:00
             */
            deliveryTime: string;
            /** Playedat */
            playedAt?: string | null;
            /**
             * Entrymode
             * @default topic
             * @enum {string}
             */
            entryMode: "news" | "topic" | "knowledge" | "skill";
            /**
             * Lengthtier
             * @default medium
             * @enum {string}
             */
            lengthTier: "short" | "medium" | "long";
        };
        /** Settings */
        Settings: {
            /**
             * Popupenabled
             * @default true
             */
            popupEnabled: boolean;
            /**
             * Popupdontshowagain
             * @default false
             */
            popupDontShowAgain: boolean;
            /**
             * Playbackrate
             * @default 1
             */
            playbackRate: number;
            /**
             * Fontsize
             * @default md
             * @enum {string}
             */
            fontSize: "sm" | "md" | "lg";
            /**
             * Theme
             * @default auto
             * @enum {string}
             */
            theme: "light" | "dark" | "auto";
            /** Preferredtopics */
            preferredTopics?: string[];
            /**
             * Defaultdeliverytime
             * @default 07:00
             */
            defaultDeliveryTime: string;
        };
        /**
         * UpdateSettingsBody
         * @description updateSettings(patch: Partial<Settings>)。全 optional，只 upsert 有給的欄位。
         */
        UpdateSettingsBody: {
            /** Popupenabled */
            popupEnabled?: boolean | null;
            /** Popupdontshowagain */
            popupDontShowAgain?: boolean | null;
            /** Playbackrate */
            playbackRate?: number | null;
            /** Fontsize */
            fontSize?: ("sm" | "md" | "lg") | null;
            /** Theme */
            theme?: ("light" | "dark" | "auto") | null;
            /** Preferredtopics */
            preferredTopics?: string[] | null;
            /** Defaultdeliverytime */
            defaultDeliveryTime?: string | null;
        };
        /**
         * UpdateVocabBody
         * @description updateVocab(id, patch{nextReview,interval,ease})。皆 optional。
         */
        UpdateVocabBody: {
            /** Nextreview */
            nextReview?: string | null;
            /** Interval */
            interval?: number | null;
            /** Ease */
            ease?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VocabItem */
        VocabItem: {
            /** Id */
            id: string;
            /** Word */
            word: string;
            /** Lemma */
            lemma: string;
            /** Pos */
            pos?: string | null;
            /** Translation */
            translation: string;
            /** Ipa */
            ipa?: string | null;
            /** Sourceepisodeid */
            sourceEpisodeId: string;
            /** Sourcelineno */
            sourceLineNo: number;
            /** Sourcetimestamp */
            sourceTimestamp: number;
            /** Createdat */
            createdAt: string;
            /**
             * Senseidx
             * @default 0
             */
            senseIdx: number;
            /** Sourcesentence */
            sourceSentence?: string | null;
            /** Sourcesentencezh */
            sourceSentenceZh?: string | null;
            /** Nextreview */
            nextReview?: string | null;
            /** Interval */
            interval?: number | null;
            /** Ease */
            ease?: number | null;
            /** Exampleen */
            exampleEn?: string | null;
            /** Examplezh */
            exampleZh?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_vocab_vocab_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_VocabItem__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_vocab_vocab_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddVocabBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_VocabItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_vocab_vocab_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_vocab_vocab_search_get: {
        parameters: {
            query?: {
                query?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_VocabItem__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_vocab_vocab__vocab_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                vocab_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vocab_vocab__vocab_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                vocab_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVocabBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_ep_settings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Settings_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_ep_settings_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Settings_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_popup_preferences_settings_reset_popup_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorites_favorites_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_str__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_favorite_favorites__slug__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favorite_favorites__slug__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_order_daily_orders__date__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Union_DailyOrder__NoneType__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_daily_order_daily_orders__date__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_daily_orders_daily_orders_get: {
        parameters: {
            query: {
                from_date: string;
                to_date: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_DailyOrder__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_daily_order_daily_orders_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveDailyOrderBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_DailyOrder_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_order_played_daily_orders__date__played_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkPlayedBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Union_DailyOrder__NoneType__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_order_episode_daily_orders__date__episode_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Union_Episode__NoneType__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_episodes_episodes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_EpisodeListItem__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_episode_episodes__slug__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Episode_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_episode_url_episodes__slug__url_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_str_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_dict_dict_lookup_get: {
        parameters: {
            query: {
                w: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Union_DictEntry__NoneType__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_ep_activity_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Activity_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_activity_ep_activity_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchActivityBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Activity_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_ep_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AccountInfo_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_ep_me_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_episodes_admin_episodes_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_AdminEpisode__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_jobs_admin_jobs_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_AdminJobQueue__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_token_usage_admin_token_usage_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AdminTokenUsageResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_order_generate_jobs_orders__date__generate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_str__str__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_notifications_notifications_pending_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_PendingNotificationOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
