"""pydantic 契約：FastAPI 與 worker 共用的資料結構。

兩類（各自一檔，這裡統一 re-export，呼叫端 import 路徑不變）：
1. 引擎契約（engine.py）— snake_case，對齊 script JSON ground truth。
2. API 契約（api.py）— camelCase alias，鏡像 frontend/src/api/types.ts。
"""

from shared.models.api import (
    AccountInfo,
    Activity,
    AdminEpisodeStats,
    AdminEpisodeStatsResponse,
    AdminEpsGenerateResponse,
    AdminJobQueue,
    CamelModel,
    Channel,
    ChannelPublic,
    ChannelTopic,
    Cue,
    DailyOrder,
    DailyOrderStatus,
    DictEntry,
    Episode,
    EpisodeListItem,
    RecommendedEpisode,
    Segment,
    Settings,
    SourceReference,
    StageMetric,
    VocabItem,
)
from shared.models.engine import (
    ANGLES,
    ENTRY_MODE_TO_TOPIC_TYPE,
    ChannelTopicCandidate,
    ClaimCheck,
    ClaimVerification,
    EntryMode,
    EpisodeCategory,
    EvidenceCard,
    JudgeVerdict,
    LengthTier,
    OutlineSegment,
    ResearchQuestion,
    ScriptFormat,
    ScriptJSON,
    ScriptLine,
    ScriptOutline,
    SourcedFact,
    SourceSnippet,
    Speaker,
    TargetVocab,
    TopicType,
    VerifiedClaim,
)

__all__ = [
    "ANGLES",
    "ENTRY_MODE_TO_TOPIC_TYPE",
    "AccountInfo",
    "Activity",
    "AdminEpisodeStats",
    "AdminEpisodeStatsResponse",
    "AdminEpsGenerateResponse",
    "AdminJobQueue",
    "CamelModel",
    "Channel",
    "ChannelPublic",
    "ChannelTopic",
    "ChannelTopicCandidate",
    "ClaimCheck",
    "ClaimVerification",
    "Cue",
    "DailyOrder",
    "DailyOrderStatus",
    "DictEntry",
    "Episode",
    "EpisodeListItem",
    "EntryMode",
    "EpisodeCategory",
    "EvidenceCard",
    "JudgeVerdict",
    "LengthTier",
    "OutlineSegment",
    "RecommendedEpisode",
    "ResearchQuestion",
    "ScriptFormat",
    "ScriptJSON",
    "ScriptLine",
    "ScriptOutline",
    "Segment",
    "Settings",
    "SourceReference",
    "SourceSnippet",
    "SourcedFact",
    "Speaker",
    "StageMetric",
    "TargetVocab",
    "TopicType",
    "VerifiedClaim",
    "VocabItem",
]
